dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.app_settings.views import *
from apps.app_auth.views import *
from apps.app_imports.views import *
from apps.app_masterData.views import *
from apps.app_kpi.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name="home"),
    path('tablero/', DashboardView.as_view(), name="dashboard"),
    path('app_auth/listUsers', UsersListView.as_view(), name="userslist"),
    path('app_auth/listUsers/create', UserView.as_view(), name="userscreate"),
    path('app_auth/listUsers/update/<int:pk>/',
         UserEditView.as_view(), name="usersedit"),

    path('app_imports/production_program_list',
         ProductionProgramListView.as_view(), name="production_program_list"),
    path('app_imports/production_program_list/create',
         ProductionProgramImport.as_view(), name="production_program_create"),
    path('app_imports/production_program_list/result',
         import_data_production_program, name="import_data_production_program"),

    path('app_imports/db_production_list',
         DBProductionListView.as_view(), name="db_production_list"),
    path('app_imports/db_production_list/create',
         DBProductionImport.as_view(), name="db_production_create"),
    path('app_imports/db_production_list/result',
         import_data_db_production, name="import_data_db_production"),

    path('app_imports/stock_homologado_list',
         StockHomologadoListView.as_view(), name="stock_homologado_list"),
    path('app_imports/stock_homologado_list/create',
         StockHomologadoImport.as_view(), name="stock_homologado_create"),
    path('app_imports/stock_homologado_list/result',
         import_data_stock_homologado, name="import_data_stock_homologado"),

    path('app_imports/stock_meta_list',
         StockMetaListView.as_view(), name="stock_meta_list"),
    path('app_imports/stock_meta_list/create',
         StockMetaImport.as_view(), name="stock_meta_create"),
    path('app_imports/stock_meta_list/result',
         import_data_stock_meta, name="import_data_stock_meta"),

    path('app_imports/stock_insumos_list',
         StockInsumosListView.as_view(), name="stock_insumos_list"),
    path('app_imports/stock_insumos_list/create',
         StockInsumosImport.as_view(), name="stock_insumos_create"),
    path('app_imports/stock_insumos_list/result',
         import_data_stock_insumos, name="import_data_stock_insumos"),

    path('app_imports/consumo_list',
         ConsumoEADListView.as_view(), name="consumo_list"),
    path('app_imports/consumo_list/create',
         ConsumoEADImport.as_view(), name="consumo_create"),
    path('app_imports/consumo_list/result',
         import_data_consumo_ead, name="import_data_consumo"),

    path('app_imports/reunion_volumen_list',
         ReunionVolumenListView.as_view(), name="reunion_volumen_list"),
    path('app_imports/reunion_volumen_list/create',
         ReunionVolumenImport.as_view(), name="reunion_volumen_create"),
    path('app_imports/reunion_volumen_list/result',
         import_data_reunion_volumen, name="import_data_reunion_volumen"),

    path('app_kpi/indicator_list',
         IndicatorListView.as_view(), name="indicator_list"),
    path('app_kpi/indicator_list/create',
         IndicatorCreateView.as_view(), name="indicator_create"),
    path('app_kpi/indicator_list/update/<str:pk>/',
         IndicatorUpdateView.as_view(), name="indicator_edit"),

    path('app_kpi/chart_list',
         ChartListView.as_view(), name="chart_list"),
    path('app_kpi/chart_list/create',
         ChartCreateView.as_view(), name="chart_create"),
    path('app_kpi/chart_list/update/<str:pk>/',
         ChartUpdateView.as_view(), name="chart_edit"),

    path('app_settings/import_file_list',
         ImportFileListView.as_view(), name="import_file_list"),
    path('app_settings/import_file_list/create',
         ImportFileCreateView.as_view(), name="import_file_create"),
    path('app_settings/import_file_list/update/<int:pk>',
         ImportFileEditView.as_view(), name="import_file_edit"),

    path('app_settings/homologation_list',
         HomologationListView.as_view(), name="homologation_list"),
    path('app_settings/homologation_list/create',
         HomologationCreateView.as_view(), name="homologation_create"),
    path('app_settings/homologation_list/update/<int:pk>',
         HomologationEditView.as_view(), name="homologation_edit"),

    path('app_master/period_type_list',
         PeriodTypeListView.as_view(), name="period_type_list"),
    path('app_master/period_type_list/create',
         PeriodTypeCreateView.as_view(), name="period_type_create"),
    path('app_master/period_type_list/update/<int:pk>/',
         PeriodTypeUpdateView.as_view(), name="period_type_edit"),

    path('app_master/period_list',
         PeriodListView.as_view(), name="period_list"),
    path('app_master/period_list/create',
         PeriodCreateView.as_view(), name="period_create"),
    path('app_master/period_list/update/<int:pk>/',
         PeriodUpdateView.as_view(), name="period_edit"),

    path('app_master/sector_list',
         SectorListView.as_view(), name="sector_list"),
    path('app_master/sector_list/create',
         SectorCreateView.as_view(), name="sector_create"),
    path('app_master/sector_list/update/<str:pk>/',
         SectorUpdateView.as_view(), name="sector_edit"),



    path('ajax/get_columns/', get_columns),
    path('ajax/get_periods/', get_periods),
    path('ajax/get_chart/', get_chart),
    path('ajax/get_charts/', get_charts),

    path('ajax/save_homologation/', save_homologation),
    path('ajax/save_import_programa_produccion/',
         save_import_programa_produccion),
    path('ajax/save_import_bd_produccion/',
         save_import_bd_produccion),
    path('ajax/save_import_stock_homologado/',
         save_import_stock_homologado),
    path('ajax/save_import_stock_meta/',
         save_import_stock_meta),
    path('ajax/save_import_stock_insumos/',
         save_import_stock_insumos),
    path('ajax/save_import_consumo_ead/',
         save_import_consumo_ead),
    path('ajax/save_import_reunion_volumen/',
         save_import_reunion_volumen),


    path('ajax/delete_chart/', delete_chart),
    path('ajax/delete_sector/', delete_sector),


    path('ajax/create_chart', create_chart),
    path('ajax/create_chart_tablero', create_chart_tablero),
    path('ajax/create_chart_tablero/before', create_chart_tablero_before),
    path('ajax/create_chart_tablero/after', create_chart_tablero_after),
    path('ajax/chart_dashboard', chart_dashboard),

    path('test', test),

]

apps/app_settings/models.py
# -*- coding: utf-8 -*-
from django.db import models
from apps.app_masterData.models import *


class ImportFile(models.Model):
    name = models.CharField(verbose_name="Nombre", max_length=50)
    first_row = models.IntegerField(
        verbose_name="Primera fila de datos", default=1)
    name_model = models.CharField(
        verbose_name="Modelo", max_length=150, null=True, blank=True)

    def __str__(self):
        return self.name


class Homologation(models.Model):
    import_file = models.ForeignKey(ImportFile, on_delete=models.CASCADE)
    db_header = models.CharField(verbose_name="Destino", max_length=50)
    entry_header = models.IntegerField(verbose_name="Entrada", default=0)

    def __str__(self):
        return '%s' % (self.import_file)

apps/app_settings/forms.py
from django import forms
from .models import *


class ImportFileForm(forms.ModelForm):

    class Meta:
        model = ImportFile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ImportFileForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['first_row'].widget.attrs['class'] = 'form-control'
        self.fields['name_model'].widget.attrs['class'] = 'form-control'


class HomologationForm(forms.ModelForm):

    class Meta:
        model = Homologation
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(HomologationForm, self).__init__(*args, **kwargs)
        self.fields['import_file'].widget.attrs['class'] = 'form-control'
        self.fields['db_header'].widget.attrs['class'] = 'form-control'
        self.fields['entry_header'].widget.attrs['class'] = 'form-control'

apps/app_settings/views.py
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.db.models import Avg

from django.contrib.auth.models import User

from .models import *
from .forms import *
from apps.app_kpi.models import *
from apps.app_masterData.models import *

import inspect
import json


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context["indicators"] = Indicator.objects.all()
        return context


class ImportFileListView(LoginRequiredMixin, ListView):
    model = ImportFile
    template_name = "app_settings/list_import_file.html"


class ImportFileCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = ImportFile
    form_class = ImportFileForm
    template_name = "app_settings/edit_import_file.html"
    success_url = "/app_settings/import_file_list"
    success_message = "%(name)s ha sido creado satisfactoriamente"


class ImportFileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = ImportFile
    form_class = ImportFileForm
    template_name = "app_settings/edit_import_file.html"
    success_url = "/app_settings/import_file_list"
    success_message = "%(name)s ha sido actualizado satisfactoriamente"


class HomologationListView(LoginRequiredMixin, ListView):
    model = Homologation
    template_name = "app_settings/list_homologation.html"


class HomologationCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Homologation
    fields = '__all__'
    template_name = "app_settings/create_homologation.html"
    success_url = "/app_settings/homologation_list"
    success_message = "%(name)s ha sido creado satisfactoriamente"

    def get_context_data(self, **kwargs):
        context = super(HomologationCreateView,
                        self).get_context_data(**kwargs)
        context["archivos"] = ImportFile.objects.all()
        return context


class HomologationEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Homologation
    form_class = HomologationForm
    template_name = "app_settings/edit_homologation.html"
    success_url = "/app_settings/homologation_list"
    success_message = "%(import_file)s ha sido actualizado satisfactoriamente"


class DashboardView(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context["sectores"] = []
        ids = []
        sectores = Sector.objects.all().order_by('id')
        for x in sectores:
            graficos = DashboardCharts.objects.values('chart_id', 'chart__size__name', 'gs_x', 'gs_y').filter(
                dashboard_id=5, show=True)
            ids = []
            for i in graficos:
                ids.append({
                    'id_chart': i['chart_id'],
                    'size': i['chart__size__name'],
                    'gs_x': i['gs_x'],
                    'gs_y': i['gs_y']
                })
            context["sectores"].append({
                'code': x.code,
                'name': x.name,
                'charts': ids
            })
        context["num_view"] = 0
        return context

templates/app_settings/create_homologation.html
{% extends 'base.html' %}
{% load static %}


{% block title_module %}

Creación homologación de datos

{% endblock title_module %}

{% block module %}
<li><a href="#">Configuración</a></li>
<li><a href="{% url 'homologation_list' %}">Lista de homologación de datos</a></li>
{% endblock module %}
{% block view %}
Crear
{% endblock view %}


{% block content %}
<div class="panel">
  <div class="panel-heading"></div>
  <form method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="panel-body">
      <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label class="control-label" for="id_import_file">Archivo a importar</label>
        <select name="id_import_file" id="id_import_file" class="form-control">
          <option value="0" selected>Seleccionar archivo...</option>
          {% for field in archivos %}
          <option value="{{field.id}}">{{field.name}}</option>
          {% endfor %}
        </select>
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text | safe }}</small>
        {% endif %}
        {% for error in field.errors %}
        <small class="text-danger pull-right">{{ error }}</small>
        {% endfor %}
      </div>
      <div class="form-group">
        <div id="result">
          <table class="table">
            <thead>
              <tr>
                <th>Destino</th>
                <th>Origen</th>
              </tr>
            </thead>
            <tbody>

            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      {% if object %}
      <button class="btn btn-danger" type="button">Eliminar</button>
      {% endif %}
      <button class="btn btn-success" type="button" id="create_homologation">
        {% if object %}
        Actualizar
        {% else %}
        Crear
        {% endif %}
      </button>
    </div>
  </form>
</div>
{% endblock content %}

templates/app_settings/edit_homologation.html
{% extends 'base.html' %}
{% load static %}


{% block title_module %}

{% if object %}
Actualización homologación de datos
{% else %}
Creación homologación de datos
{% endif %}

{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
<li><a href="{% url 'import_file_list' %}">Lista de homologación de datos</a></li>
{% endblock module %}
{% block view %}
{% if object %}
Actualizar
{% else %}
Crear
{% endif %}
{% endblock view %}


{% block content %}
<div class="panel">
  <div class="panel-heading"></div>
  <form method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="panel-body">
      {% for field in form %}
      <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label class="control-label" for="{{field.name}}">{{field.label}}</label>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text | safe }}</small>
        {% endif %}
        {% for error in field.errors %}
        <small class="text-danger pull-right">{{ error }}</small>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
    <div class="panel-footer">
      {% if object %}
      <button class="btn btn-danger" type="button">Eliminar</button>
      {% endif %}
      <button class="btn btn-success" type="submit">
        {% if object %}
        Actualizar
        {% else %}
        Crear
        {% endif %}
      </button>
    </div>
  </form>
</div>
{% endblock content %}

templates/app_settings/edit_import_file.html
{% extends 'base.html' %}
{% load static %}


{% block title_module %}

{% if object %}
Actualización archivo a importar
{% else %}
Creación archivo a importar
{% endif %}

{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
<li><a href="{% url 'import_file_list' %}">Lista de archivos a importar</a></li>
{% endblock module %}
{% block view %}
{% if object %}
Actualizar
{% else %}
Crear
{% endif %}
{% endblock view %}


{% block content %}
<div class="panel">
  <div class="panel-heading"></div>
  <form method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="panel-body">
      {% for field in form %}
      <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label class="control-label" for="{{field.name}}">{{field.label}}</label>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text | safe }}</small>
        {% endif %}
        {% for error in field.errors %}
        <small class="text-danger pull-right">{{ error }}</small>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
    <div class="panel-footer">
      {% if object %}
      <button class="btn btn-danger" type="button">Eliminar</button>
      {% endif %}
      <button class="btn btn-success" type="submit">
        {% if object %}
        Actualizar
        {% else %}
        Crear
        {% endif %}
      </button>
    </div>
  </form>
</div>
{% endblock content %}

templates/app_settings/edit_period.html
{% extends 'base.html' %}
{% load static %}


{% block title_module %}

{% if object %}
Actualización periodos
{% else %}
Creación periodos
{% endif %}

{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
<li><a href="{% url 'period_list' %}">Lista de periodos</a></li>
{% endblock module %}
{% block view %}
{% if object %}
Actualizar
{% else %}
Crear
{% endif %}
{% endblock view %}

{% block content %}
<div class="panel">
  <div class="panel-heading"></div>
  <form method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="panel-body">
      {% for field in form %}
      <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label class="control-label" for="{{field.name}}">{{field.label}}</label>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text | safe }}</small>
        {% endif %}
        {% for error in field.errors %}
        <small class="text-danger pull-right">{{ error }}</small>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
    <div class="panel-footer">
      {% if object %}
      <button class="btn btn-danger" type="button">Eliminar</button>
      {% endif %}
      <button class="btn btn-success" type="submit">
        {% if object %}
        Actualizar
        {% else %}
        Crear
        {% endif %}
      </button>
    </div>
  </form>
</div>
{% endblock content %}

templates/app_settings/edit_period_type.html
{% extends 'base.html' %}
{% load static %}


{% block title_module %}

{% if object %}
Actualización tipos de periodos
{% else %}
Creación tipos de periodos
{% endif %}

{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
<li><a href="{% url 'period_type_list' %}">Lista de tipos de periodos</a></li>
{% endblock module %}
{% block view %}
{% if object %}
Actualizar
{% else %}
Crear
{% endif %}
{% endblock view %}

{% block content %}
<div class="panel">
  <div class="panel-heading"></div>
  <form method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="panel-body">
      {% for field in form %}
      <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label class="control-label" for="{{field.name}}">{{field.label}}</label>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text | safe }}</small>
        {% endif %}
        {% for error in field.errors %}
        <small class="text-danger pull-right">{{ error }}</small>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
    <div class="panel-footer">
      {% if object %}
      <button class="btn btn-danger" type="button">Eliminar</button>
      {% endif %}
      <button class="btn btn-success" type="submit">
        {% if object %}
        Actualizar
        {% else %}
        Crear
        {% endif %}
      </button>
    </div>
  </form>
</div>
{% endblock content %}

templates/app_settings/list_homologation.html
{% extends 'base.html' %}
{% load static %}


{% block extrahead %}
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
{% endblock extrahead %}



{% block title_module %}
Homologación de datos
{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
{% endblock module %}
{% block view %}
Lista de homologación de datos
{% endblock view %}


{% block content %}

{% if messages %}
<div class="alert alert-success">
  {% for message in messages %}
  {{message}}
  {% endfor %}
</div>
{% endif %}

<div class="panel">
  <div class="panel-heading">
    <div class="panel-control">
      <a href="{% url 'homologation_create' %}" class="btn btn-primary btn-labeled"><i
          class="btn-label demo-pli-add"></i>
        Agregar homologación de datos</a>
    </div>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-bordered datatable-list" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th class="active">Id</th>
          <th class="active">Archivo a importar</th>
          <th class="active">Entrada</th>
          <th class="active">Salida</th>
        </tr>
      </thead>
      <tbody>
        {% for self in object_list %}
        <tr data-url="{% url 'homologation_edit' self.id %}">
          <td>{{self.id}}</td>
          <td>{{self.import_file}}</td>
          <td>Columna({{self.entry_header}})</td>
          <td>{{self.db_header}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}


{% block extrascript %}
<script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/app/tables-datatables.js' %}"></script>
{% endblock extrascript %}

templates/app_settings/list_import_file.html
{% extends 'base.html' %}
{% load static %}


{% block extrahead %}
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
{% endblock extrahead %}



{% block title_module %}
Archivos de importación
{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
{% endblock module %}
{% block view %}
Lista de archivos de importación
{% endblock view %}


{% block content %}

{% if messages %}
<div class="alert alert-success">
  {% for message in messages %}
  {{message}}
  {% endfor %}
</div>
{% endif %}

<div class="panel">
  <div class="panel-heading">
    <div class="panel-control">
      <a href="{% url 'import_file_create' %}" class="btn btn-primary btn-labeled"><i
          class="btn-label demo-pli-add"></i>
        Agregar archivo a importar</a>
    </div>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-bordered datatable-list" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th class="active">Id</th>
          <th class="active">Nombre</th>
          <th class="active">1ra fila de datos</th>
          <th class="active">Modelo</th>
        </tr>
      </thead>
      <tbody>
        {% for self in object_list %}
        <tr data-url="{% url 'import_file_edit' self.id %}">
          <td>{{self.id}}</td>
          <td>{{self.name}}</td>
          <td>{{self.first_row}}</td>
          <td>{{self.name_model}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}


{% block extrascript %}
<script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/app/tables-datatables.js' %}"></script>
{% endblock extrascript %}

templates/app_settings/list_period.html
{% extends 'base.html' %}
{% load static %}


{% block extrahead %}
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
{% endblock extrahead %}



{% block title_module %}
Periodos
{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
{% endblock module %}
{% block view %}
Lista de periodos
{% endblock view %}


{% block content %}

{% if messages %}
<div class="alert alert-success">
  {% for message in messages %}
  {{message}}
  {% endfor %}
</div>
{% endif %}

<div class="panel">
  <div class="panel-heading">
    <div class="panel-control">
      <a href="{% url 'period_create' %}" class="btn btn-primary btn-labeled"><i class="btn-label demo-pli-add"></i>
        Agregar periodo</a>
    </div>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-bordered datatable-list" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th class="active">Id</th>
          <th class="active">Tipo de periodo</th>
          <th class="active">Periodo</th>
        </tr>
      </thead>
      <tbody>
        {% for self in object_list %}
        <tr data-url="{% url 'period_edit' self.id %}">
          <td>{{self.id}}</td>
          <td>{{self.period_type}}</td>
          <td>{{self.name}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}


{% block extrascript %}
<script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/app/tables-datatables.js' %}"></script>
{% endblock extrascript %}

templates/app_settings/list_period_type.html
{% extends 'base.html' %}
{% load static %}


{% block extrahead %}
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
{% endblock extrahead %}



{% block title_module %}
Tipos de periodos
{% endblock title_module %}
{% block module %}
<li><a href="#">Configuración</a></li>
{% endblock module %}
{% block view %}
Lista de tipos de periodos
{% endblock view %}


{% block content %}

{% if messages %}
<div class="alert alert-success">
  {% for message in messages %}
  {{message}}
  {% endfor %}
</div>
{% endif %}

<div class="panel">
  <div class="panel-heading">
    <div class="panel-control">
      <a href="{% url 'period_type_create' %}" class="btn btn-primary btn-labeled"><i
          class="btn-label demo-pli-add"></i>
        Agregar tipo de periodo</a>
    </div>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-bordered datatable-list" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th class="active">Id</th>
          <th class="active">Nombre</th>
        </tr>
      </thead>
      <tbody>
        {% for self in object_list %}
        <tr data-url="{% url 'period_type_edit' self.id %}">
          <td>{{self.id}}</td>
          <td>{{self.period}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}


{% block extrascript %}
<script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/app/tables-datatables.js' %}"></script>
{% endblock extrascript %}